### ISSUE TITLE
CH347 JTAG not working?

### ISSUE THREAD

**Issue by aystarik** [WCHSoftGroup/ch347#13]
Hi, I'm trying to make CH347 JTAG work with openFPGALoader, but there are problems.
The chip I have reply to 0xD2 command with the same amount of bytes as command length itself, thus giving twice the amount of TDO states (command outputs two bits per TDI bit). Your code reads the response as if only one byte per bit is present.
The other problem is that if I write two 0xD4/0xD2 messages immediately one after the other, I get reply for the first and timeout for the second, if timeout is about 100ms, then third 0xD4/0xD2 get in reply data for both second and itself. I've tried to add 0xD1 command to the message to set TCK low, it does not change anything...
Could  you please help with this?

**Comment by aystarik** [comment]
Here is the message log to/from CH347 then there are 100ms delays after each 0xD4/0xD2 exchange

obuf[9] = {d0 06 00 00 02 00 00 00 00 }

ibuf[4] = {d0 01 00 00 }

JTAG TCK frequency set to 8 MHz

obuf[16] = {d1 0d 00 12 13 12 13 12 13 12 13 12 13 12 13 12 }

obuf[12] = {d1 09 00 10 11 12 13 10 11 10 11 10 }

Raw IDCODE:
obuf[7] = {d4 04 00 ff ff ff ff }

ibuf[7] = {d4 04 00 3d 56 00 10 }

- 0 -> 0x1000563d
obuf[7] = {d4 04 00 ff ff ff ff }

ibuf[7] = {d4 04 00 a3 07 00 79 }

- 1 -> 0x790007a3
obuf[7] = {d4 04 00 ff ff ff ff }

ibuf[7] = {d4 04 00 ff ff ff ff }

- 2 -> 0xffffffff
obuf[7] = {d4 04 00 ff ff ff ff }

ibuf[7] = {d4 04 00 ff ff ff ff }

- 3 -> 0xffffffff
obuf[6] = {d4 03 00 ff ff ff }

ibuf[6] = {d4 03 00 ff ff ff }

obuf[20] = {d2 11 00 10 11 10 11 10 11 10 11 10 11 10 11 10 11 12 13 12 }

ibuf[20] = {d2 11 00 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 01 }

- 4 -> 0xffffffff
obuf[16] = {d1 0d 00 12 13 12 13 12 13 12 13 12 13 12 13 12 }

**Comment by aystarik** [comment]
obuf[9] = {d0 06 00 00 02 00 00 00 00 }
ibuf[4] = {d0 01 00 00 }

JTAG TCK frequency set to 8 MHz

obuf[16] = {d1 0d 00 12 13 12 13 12 13 12 13 12 13 12 13 12 }
obuf[12] = {d1 09 00 10 11 12 13 10 11 10 11 10 }

Raw IDCODE:
obuf[7] = {d4 04 00 ff ff ff ff }
ibuf[7] = {d4 04 00 3d 56 00 10 }

- 0 -> 0x1000563d
obuf[7] = {d4 04 00 ff ff ff ff }
ibuf[0] = {}  ---- no data returned for the second command

obuf[7] = {d4 04 00 ff ff ff ff }
ibuf[14] = {d4 04 00 a3 07 00 79 d4 04 00 ff ff ff ff } -- third command gets data from both second and itself

**Comment by EasyDevKits** [comment]
How did you solve this issue?

**Comment by aystarik** [comment]
It appears that there are two versions of the chip, 1.4x and 2.4x. In later
one jtag works, but i2c in mode 3 stops working -- clk line is left in
input state, it is possible to return it to output via gpio commands, but
i'm not sure if it is right thing to do... so choose your pioson...

**Comment by EasyDevKits** [comment]
Thanks @aystarik. I can read via

```
jtag_libusb_control_transfer(ch347_handle,
				LIBUSB_ENDPOINT_IN | LIBUSB_REQUEST_TYPE_VENDOR | LIBUSB_RECIPIENT_DEVICE,
				VENDOR_VERSION, 0, 0, &firmwareVersion, sizeof(firmwareVersion), usb_write_timeout, NULL)
```

that I've firmware version 0x41 (decimal 65, ascii 'A'). Is that a 1.4x or 2.4x chip? Or how can I read the chip version?

**Comment by aystarik** [comment]
https://github.com/aystarik/openFPGALoader/blob/2f9be05ba0de05244619a67eb3f93a57dc1dd289/src/ch347jtag.cpp#L206C8-L206C8

**Comment by EasyDevKits** [comment]
I've a 2.41 chip, but it's not working. I've analyzed the signals with a logic analyzer and found that for instance for

`obuf[7] = {d4 04 00 ff ff ff ff }`

only 12 TCK pulses are output. But it should be 4x8=32 TCK pulses.

![Bildschirmfoto vom 2023-10-05 00-31-44](https://github.com/WCHSoftGroup/ch347/assets/142944713/e30ceb4c-e77e-4039-b5f3-7abf5dbff178)

The 12 TCK pulses are unregulary distributed over 4.75µs. One pulse is 125ns or 0.125µs wide. So it would be possible to send 32 pulses = 32x125ns=4000ns=4µs. But most of the pulses are missing.

I'll now try to get it working with the D2 command (bit operations and read) only. That should work with all chip versions.

**Comment by aystarik** [comment]
First, check the wires, i' ve had many "not working" cases which ended up being loose connections.

**Comment by EasyDevKits** [comment]
Good point. It's not the wiring that's wrong. The logic analyzer is too slow and missed some TCK pulses. But by the way I've implemented also a mode for older chips where the byte wise commands are not working correctly. To get it working with my target chip an ESP32 dual core chip it took a few evenings to found that the ch347 source code didn't handle multiple TAPs correctly. Now I've fixed the bug and it's also working for the ESP32 dual core chips.

Working version is here: https://github.com/EasyDevKits/openocd-easydevkits

**Comment by aystarik** [comment]
It seems you do have some programming documentation for the chip, any chance you can share it?

**Comment by EasyDevKits** [comment]
I've found out how it's working in various source codes.

Now, I've written a little documentation for the JTAG part of the CH347: https://www.easydevkits.com/wch-ch347-jtag-interface/

**Comment by aystarik** [comment]
thanks,it appears I've missed openocd update with SWD mode. in your doc there are several wrong copy-pasts of the length field 0x05 where I believe should be something else. For GPIO you might find something useful in my driver : https://github.com/aystarik/ch347_vcp/blob/main/gpio-ch347.c

**Comment by EasyDevKits** [comment]
Thanks for the review of the documentation. Now I've mentioned the known command numbers for SWD but I've not digged into it and can't describe this. For the GPIO I've updated the documentation and I'm also remembering that my knowledge about GPIO command comes already from your driver. In the updated documentation at https://www.easydevkits.com/wch-ch347-jtag-interface/ I've also mentioned you work.
