### ISSUE TITLE
windows11 使用openocd.exe ch347异常，linux版则正常

### ISSUE THREAD

**Issue by yangbonis** [WCHSoftGroup/ch347#30]

**Comment by yangbonis** [comment]
一个警告，不知是否有关系
![image](https://github.com/WCHSoftGroup/ch347/assets/53347571/1c8ccc87-52a4-4563-a5eb-f39730b0790f)

**Comment by yangbonis** [comment]
![Uploading image.png…]()

**Comment by yangbonis** [comment]
![image](https://github.com/WCHSoftGroup/ch347/assets/53347571/ea8ddbbd-f0d1-4310-8850-704a4dcd8937)

**Comment by AIOT-CAT** [comment]
参考这个信息，https://blog.csdn.net/OIDCAT/article/details/126876159，补齐cygwin的缺失，也可以用msys2来编译，方便下载依赖。

**Comment by yangbonis** [comment]
![image](https://github.com/WCHSoftGroup/ch347/assets/53347571/3637abea-ca90-4d9a-8f66-d5454b14a5af)
正确编译后，仍然会出面上面的现象。

**Comment by yangbonis** [comment]
最新版openocd编window版，其它的芯片可以正常使用，但是ch347.c文件在最新版会有一些编译错误，需要移植。

**Comment by AIOT-CAT** [comment]
您描述的问题都是集中在编译上，且与CH347无直接关系。编译过程中提示warn不影响编译出可执行文件。另外您说ch347.c在最新版本会有编译错误，此处不详实，若出现错误则无法输出exe文件，且同样文件我构建编译是正常，功能也是正常。

**Comment by hkdoll123** [comment]
> 您描述的问题都是集中在编译上，且与CH347无直接关系。编译过程中提示warn不影响编译出可执行文件。另外您说ch347.c在最新版本会有编译错误，此处不详实，若出现错误则无法输出exe文件，且同样文件我构建编译是正常，功能也是正常。

大佬，能看看您的‘https://github.com/AIOT-CAT/xvcd-ch347’的issues么？  我想请教点问题

**Comment by yangbonis** [comment]
![image](https://github.com/WCHSoftGroup/ch347/assets/53347571/1775400c-5a4a-4775-8631-c96092672c65)

你们使用的是windows11吗？我只能得到segmentation fault

**Comment by yangbonis** [comment]
![image](https://github.com/WCHSoftGroup/ch347/assets/53347571/ab42d257-9ee9-48b5-8de5-5cb81bee41fd)
请细的信息如下

**Comment by ZhiyuanYuanNJ** [comment]
@yangbonis Windows使用的是厂商驱动，你那是不是还是用的libusb驱动？

**Comment by yangbonis** [comment]
> @yangbonis Windows使用的是厂商驱动，你那是不是还是用的libusb驱动？

我是完全按照你们的文档来操作的。厂商驱动是ch347提供的windows驱动吗？如何下载

**Comment by ZhiyuanYuanNJ** [comment]
> > @yangbonis Windows使用的是厂商驱动，你那是不是还是用的libusb驱动？
> 
> 我是完全按照你们的文档来操作的。厂商驱动是ch347提供的windows驱动吗？如何下载
沁恒的官方驱动在官网有，[https://www.wch.cn/downloads/CH341PAR_EXE.html](https://www.wch.cn/downloads/CH341PAR_EXE.html)

**Comment by yangbonis** [comment]
> > > @yangbonis Windows使用的是厂商驱动，你那是不是还是用的libusb驱动？
> > 
> > 
> > 我是完全按照你们的文档来操作的。厂商驱动是ch347提供的windows驱动吗？如何下载
> > 沁恒的官方驱动在官网有，https://www.wch.cn/downloads/CH341PAR_EXE.html

感谢，已经可以使用了
