### ISSUE TITLE
Missing code for CH347DLL.dll

### ISSUE THREAD

**Issue by zingo** [WCHSoftGroup/ch347#8]
Hi
Would it be possible to add the code in the **CH347DLL.dll** I think it would be needed to make this work on Linux and Mac (and maybe even Arm based Window). 
Also it would be needed if this is going to be upstreamed and included in the openocd project out of the box some day.
Thanks for your time!

**Comment by AIOT-CAT** [comment]
Support for linux and other systems will be added in the near future. Thank you for your suggestions.

**Comment by 981213** [comment]
@zingo There's an OUT endpoint and an IN endpoint for JTAG. CH347Write and CH347Read simply writes to/reads from the corresponding endpoint. I guess it shouldn't be too hard to capture and hard-code an init packet and replace everything else with libusb.

**Comment by EasyDevKits** [comment]
For Linux it's already working without CH347DLL.dll. The Linux version uses libusb directly.

**Comment by zingo** [comment]
Supernice info, great! I don't have any ch347 projects right now ongoing so I will not be able to test this and will just close the ticket!
